GH_TUPLE=	\
		apparentlymart:go-textseg:v13.0.0:apparentlymart_go_textseg_v13/vendor/github.com/apparentlymart/go-textseg/v13 \
		golang:text:v0.8.0:golang_text/vendor/golang.org/x/text \
		google:go-cmp:v0.5.9:google_go_cmp/vendor/github.com/google/go-cmp \
		hashicorp:go-version:v1.6.0:hashicorp_go_version/vendor/github.com/hashicorp/go-version \
		hashicorp:terraform-exec:v0.18.1:hashicorp_terraform_exec/vendor/github.com/hashicorp/terraform-exec \
		hashicorp:terraform-json:v0.16.0:hashicorp_terraform_json/vendor/github.com/hashicorp/terraform-json \
		mitchellh:colorstring:d06e56a500db:mitchellh_colorstring/vendor/github.com/mitchellh/colorstring \
		zclconf:go-cty:v1.13.0:zclconf_go_cty/vendor/github.com/zclconf/go-cty
