GH_TUPLE=	\
		go-yaml:yaml:v2.4.0:go_yaml_yaml/vendor/gopkg.in/yaml.v2 \
		golang:crypto:86341886e292:golang_crypto/vendor/golang.org/x/crypto \
		golang:lint:6edffad5e616:golang_lint/vendor/golang.org/x/lint \
		golang:mod:v0.5.1:golang_mod/vendor/golang.org/x/mod \
		golang:net:69e39bad7dc2:golang_net/vendor/golang.org/x/net \
		golang:sys:1d35b9e2eb4e:golang_sys/vendor/golang.org/x/sys \
		golang:text:v0.3.7:golang_text/vendor/golang.org/x/text \
		golang:tools:v0.1.9:golang_tools/vendor/golang.org/x/tools \
		golang:xerrors:5ec99f83aff1:golang_xerrors/vendor/golang.org/x/xerrors \
		google:uuid:v1.3.0:google_uuid/vendor/github.com/google/uuid \
		gookit:color:v1.5.0:gookit_color/vendor/github.com/gookit/color \
		lib:pq:v1.10.4:lib_pq/vendor/github.com/lib/pq \
		mozilla:tls-observatory:7bc42856d2e5:mozilla_tls_observatory/vendor/github.com/mozilla/tls-observatory \
		nbutton23:zxcvbn-go:fa2cb2858354:nbutton23_zxcvbn_go/vendor/github.com/nbutton23/zxcvbn-go \
		onsi:ginkgo:v2.1.3:onsi_ginkgo_v2/vendor/github.com/onsi/ginkgo/v2 \
		onsi:gomega:v1.18.1:onsi_gomega/vendor/github.com/onsi/gomega \
		xo:terminfo:ca9a967f8778:xo_terminfo/vendor/github.com/xo/terminfo
