GH_TUPLE=	fatih:camelcase:v1.0.0:fatih_camelcase/vendor/github.com/fatih/camelcase \
		fatih:structtag:v1.2.0:fatih_structtag/vendor/github.com/fatih/structtag \
		golang:tools:6c1c5e93cdc1:golang_tools/vendor/golang.org/x/tools
