GH_TUPLE=	\
		bmatcuk:doublestar:v4.7.1:bmatcuk_doublestar_v4/vendor/github.com/bmatcuk/doublestar/v4 \
		braydonk:yaml:v0.9.0:braydonk_yaml/vendor/github.com/braydonk/yaml \
		golang:text:v0.14.0:golang_text/vendor/golang.org/x/text \
		google:go-cmp:v0.6.0:google_go_cmp/vendor/github.com/google/go-cmp \
		mitchellh:mapstructure:v1.5.0:mitchellh_mapstructure/vendor/github.com/mitchellh/mapstructure \
		sabhiram:go-gitignore:525f6e181f06:sabhiram_go_gitignore/vendor/github.com/sabhiram/go-gitignore \
		santhosh-tekuri:jsonschema:v6.0.1:santhosh_tekuri_jsonschema_v6/vendor/github.com/santhosh-tekuri/jsonschema/v6
