GH_TUPLE=	\
		gdamore:encoding:v1.0.1:gdamore_encoding/vendor/github.com/gdamore/encoding \
		gdamore:tcell:v1.4.0:gdamore_tcell/vendor/github.com/gdamore/tcell \
		golang:sys:v0.26.0:golang_sys/vendor/golang.org/x/sys \
		golang:term:v0.25.0:golang_term/vendor/golang.org/x/term \
		golang:text:v0.19.0:golang_text/vendor/golang.org/x/text \
		lucasb-eyer:go-colorful:v1.2.0:lucasb_eyer_go_colorful/vendor/github.com/lucasb-eyer/go-colorful \
		mattn:go-runewidth:v0.0.16:mattn_go_runewidth/vendor/github.com/mattn/go-runewidth \
		rivo:uniseg:v0.4.7:rivo_uniseg/vendor/github.com/rivo/uniseg
