PORTNAME=	dump
PORTVERSION=	0.4
DISTVERSIONSUFFIX=	-0.23.b44.el7
CATEGORIES=	sysutils linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	Programs for backing up and restoring ext2/ext3 filesystems (CentOS ${LINUX_DIST_VER})

LICENSE=	GPLv3+

USES=		linux:c7
USE_LINUX_RPM=	nolib
OPTIONS_DEFINE=	DOCS
PLIST=		${PKGDIR}/pkg-plist

.include <bsd.port.mk>
