GH_TUPLE=	\
		cpuguy83:go-md2man:f79a8a8ca69d:cpuguy83_go_md2man_v2/vendor/github.com/cpuguy83/go-md2man/v2 \
		dustin:go-humanize:v1.0.0:dustin_go_humanize/vendor/github.com/dustin/go-humanize \
		golang:crypto:5c72a883971a:golang_crypto/vendor/golang.org/x/crypto \
		golang:sys:97732733099d:golang_sys/vendor/golang.org/x/sys \
		russross:blackfriday:v2.0.1:russross_blackfriday_v2/vendor/github.com/russross/blackfriday/v2 \
		shurcooL:sanitized_anchor_name:v1.0.0:shurcool_sanitized_anchor_name/vendor/github.com/shurcooL/sanitized_anchor_name \
		urfave:cli:v2.2.0:urfave_cli_v2/vendor/github.com/urfave/cli/v2

GL_TUPLE=	poldi1405:go-ansi:27103de357e7fd1f2cd7142a32473e0ba35a48d3:poldi1405_go_ansi/vendor/gitlab.com/poldi1405/go-ansi \
		poldi1405:go-indicators:9b373aa411a58e878c0dd9a3e43647a07a1890c7:poldi1405_go_indicators/vendor/gitlab.com/poldi1405/go-indicators
