# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>

PKGNAMESUFFIX=	-node10

CONFLICTS_INSTALL=	npm npm-node14 npm-node16 npm-node17

USES=		nodejs:10,run

MASTERDIR=	${PORTSDIR}/www/npm

.include "${MASTERDIR}/Makefile"
