PORTNAME=	ini2json
PORTVERSION=	20140121
CATEGORIES=	local converters

MAINTAINER=	none@freebsd.org
COMMENT=	Simple INI to JSON converter
WWW=		https://github.com/${GH_ACCOUNT}/${GH_PROJECT}

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		cmake ninja

USE_GITHUB=	yes
GH_ACCOUNT=	Anubisss
GH_TAGNAME=	5504b98

PLIST_FILES=	bin/${PORTNAME}

.include <bsd.port.mk>
