PORTNAME=	Devel-OverrideGlobalRequire
PORTVERSION=	0.001
CATEGORIES=	devel perl5 local
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	none@FreeBSD.org
COMMENT=	Override CORE::GLOBAL::require safely
WWW=		https://metacpan.org/pod/Devel::OverrideGlobalRequire

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

NO_ARCH=	yes

.include "../Mk/${USES:Mperl*}.mk"
.include <bsd.port.mk>
