PORTNAME=	Devel-OverrideGlobalRequire
PORTVERSION=	0.001
CATEGORIES=	devel perl5 local
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	none@FreeBSD.org
COMMENT=	Override CORE::GLOBAL::require safely
WWW=		https://metacpan.org/pod/Devel::OverrideGlobalRequire

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

BUILD_DEPENDS=	p5-PathTools>=0:devel/p5-PathTools
TEST_DEPENDS=	p5-Test-Simple>=0.88:devel/p5-Test-Simple

USES=		perl5
USE_PERL5=	configure

NO_ARCH=	yes

.include <bsd.port.mk>
