GH_TUPLE=	golang:net:244492dfa37a:golang_net/vendor/golang.org/x/net \
		golang:text:v0.3.2:golang_text/vendor/golang.org/x/text \
		sethgrid:pester:68a33a018ad0:sethgrid_pester/vendor/github.com/sethgrid/pester
