GH_TUPLE=	golang:net:v0.7.0:golang_net/vendor/golang.org/x/net \
		golang:text:v0.7.0:golang_text/vendor/golang.org/x/text \
		sethgrid:pester:v1.2.0:sethgrid_pester/vendor/github.com/sethgrid/pester
