GH_TUPLE=	\
		BurntSushi:toml:a339e1f7089c:burntsushi_toml/vendor/github.com/BurntSushi/toml \
		golang:exp:9a3e6036ecaa:golang_exp/vendor/golang.org/x/exp \
		golang:mod:v0.35.0:golang_mod/vendor/golang.org/x/mod \
		golang:sync:v0.20.0:golang_sync/vendor/golang.org/x/sync \
		golang:tools:19499e7caabc:golang_tools/vendor/golang.org/x/tools \
		google:go-cmp:v0.7.0:google_go_cmp/vendor/github.com/google/go-cmp
		# Mirrors for the following packages are not currently known, please look them up and handle these tuples manually:
		#	::2478ac86f678:group_name/vendor/golang.org/x/exp/typeparams (from go.googlesource.com/exp/typeparams@2478ac86f678)
		#	::v0.1.1-deprecated:group_name/vendor/golang.org/x/tools/go/expect (from go.googlesource.com/tools/go/expect@v0.1.1-deprecated)
