PORTNAME=	Hash-SafeKeys
PORTVERSION=	0.04
CATEGORIES=	devel perl5 local
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	none@FreeBSD.org
COMMENT=	Get hash contents without resetting each iterator
WWW=		https://metacpan.org/pod/Hash::SafeKeys

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

NO_ARCH=	yes

.include "../Mk/${USES:Mperl*}.mk"
.include <bsd.port.mk>
