PORTNAME=	Hash-SafeKeys
PORTVERSION=	0.04
CATEGORIES=	devel perl5 local
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	none@FreeBSD.org
COMMENT=	Get hash contents without resetting each iterator
WWW=		https://metacpan.org/pod/Hash::SafeKeys

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Simple>=0.88:devel/p5-Test-Simple

USES=		perl5
USE_PERL5=	configure

NO_ARCH=	yes

.include <bsd.port.mk>
