PORTNAME=	xfsprogs
PORTVERSION=	4.5.0
DISTVERSIONSUFFIX=	-22.el7
CATEGORIES=	sysutils linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	Utilities for managing the XFS filesystem (CentOS ${LINUX_DIST_VER})

LICENSE=	GPLv3+

USES=		linux:c7
USE_LINUX_RPM=	nolib
OPTIONS_DEFINE=	DOCS
PLIST=		${PKGDIR}/pkg-plist

.include <bsd.port.mk>
