PORTNAME=	seespot
PORTVERSION=	0.0.1
PORTREVISION=	1
CATEGORIES=	local sysutils

MAINTAINER=	none@freebsd.org
COMMENT=	Watches for a termination notification in AWS
WWW=		https://github.com/${GH_ACCOUNT}/${GH_PROJECT}

LICENSE=	MPL20
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		go
USE_GITHUB=	yes
GH_ACCOUNT=	opszero

#No longer maintained
GH_TAGNAME=	8280e32

GO_PKGNAME=	github.com/${GH_ACCOUNT}/${GH_PROJECT}
PLIST_FILES=	bin/${PORTNAME}

.include <bsd.port.mk>
