GH_TUPLE=	\
		agext:levenshtein:v1.2.3:agext_levenshtein/vendor/github.com/agext/levenshtein \
		apparentlymart:go-textseg:v15.0.0:apparentlymart_go_textseg_v15/vendor/github.com/apparentlymart/go-textseg/v15 \
		apparentlymart:go-textseg:v17.0.1:apparentlymart_go_textseg_v17/vendor/github.com/apparentlymart/go-textseg/v17 \
		golang:mod:v0.40.0:golang_mod/vendor/golang.org/x/mod \
		golang:sync:v0.22.0:golang_sync/vendor/golang.org/x/sync \
		golang:text:v0.41.0:golang_text/vendor/golang.org/x/text \
		golang:tools:v0.49.0:golang_tools/vendor/golang.org/x/tools \
		google:go-cmp:v0.7.0:google_go_cmp/vendor/github.com/google/go-cmp \
		hashicorp:hcl:v2.24.0:hashicorp_hcl_v2/vendor/github.com/hashicorp/hcl/v2 \
		mitchellh:go-wordwrap:v1.0.1:mitchellh_go_wordwrap/vendor/github.com/mitchellh/go-wordwrap \
		omilevskyi:go:v0.1.26:omilevskyi_go/vendor/github.com/omilevskyi/go \
		zclconf:go-cty:v1.19.0:zclconf_go_cty/vendor/github.com/zclconf/go-cty
