GH_TUPLE=	\
		go-yaml:yaml:eeeca48fe776:go_yaml_yaml/vendor/gopkg.in/yaml.v3 \
		hashicorp:hcl:v1.0.0:hashicorp_hcl/vendor/github.com/hashicorp/hcl \
		sclevine:go-toml:ed50a274ac56:sclevine_go_toml/vendor/github.com/pelletier/go-toml \

