GH_TUPLE=	Vonage:gosrvlib:v1.101.5:vonage_gosrvlib/vendor/github.com/Vonage/gosrvlib \
		golang:sync:v0.8.0:golang_sync/vendor/golang.org/x/sync \
		huandu:skiplist:v1.2.1:huandu_skiplist/vendor/github.com/huandu/skiplist
