GH_TUPLE=	\
		davecgh:go-spew:d8f796af33cc:davecgh_go_spew/vendor/github.com/davecgh/go-spew \
		golang:sync:v0.19.0:golang_sync/vendor/golang.org/x/sync \
		huandu:skiplist:v1.2.1:huandu_skiplist/vendor/github.com/huandu/skiplist \
		jellydator:ttlcache:v3.4.0:jellydator_ttlcache_v3/vendor/github.com/jellydator/ttlcache/v3 \
		pmezard:go-difflib:5d4384ee4fb2:pmezard_go_difflib/vendor/github.com/pmezard/go-difflib
