PORTNAME=	click-spinner
PORTVERSION=    0.1.10
CATEGORIES=	local devel python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	none@freebsd.org
COMMENT=	Show that your command line app is active
WWW=		https://github.com/click-contrib/click-spinner

LICENSE=	MIT

USES=		python
USE_PYTHON=	autoplist concurrent pep517

.include <bsd.port.mk>
