GH_TUPLE=	golang:sys:v0.47.0:golang_sys/vendor/golang.org/x/sys \
		mattn:go-isatty:v0.0.24:mattn_go_isatty/vendor/github.com/mattn/go-isatty \
		omilevskyi:go:v0.1.1:omilevskyi_go/vendor/github.com/omilevskyi/go
