GH_TUPLE=	golang:net:v0.24.0:golang_net/vendor/golang.org/x/net \
		golang:tools:v0.20.0:golang_tools/vendor/golang.org/x/tools \
		skratchdot:open-golang:eef842397966:skratchdot_open_golang/vendor/github.com/skratchdot/open-golang
