PORTNAME=	attr
PORTVERSION=	2.4.46
DISTVERSIONSUFFIX=	-13.el7
CATEGORIES=	sysutils linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	Utilities for managing filesystem extended attributes (CentOS ${LINUX_DIST_VER})

LICENSE=	GPLv3+

USES=		linux:c7
USE_LINUX_RPM=	nolib
OPTIONS_DEFINE=	DOCS
PLIST=		${PKGDIR}/pkg-plist

.include <bsd.port.mk>
