GH_TUPLE=	\
		golang:mod:v0.17.0:golang_mod/vendor/golang.org/x/mod \
		golang:net:v0.35.0:golang_net/vendor/golang.org/x/net \
		golang:text:v0.22.0:golang_text/vendor/golang.org/x/text \
		golang:tools:e35e4ccd0d2d:golang_tools/vendor/golang.org/x/tools \
		iancoleman:strcase:v0.3.0:iancoleman_strcase/vendor/github.com/iancoleman/strcase \
		lyft:protoc-gen-star:496ad1ac90a4:lyft_protoc_gen_star_v2/vendor/github.com/lyft/protoc-gen-star/v2 \
		protocolbuffers:protobuf-go:v1.36.5:protocolbuffers_protobuf_go/vendor/google.golang.org/protobuf \
		spf13:afero:v1.10.0:spf13_afero/vendor/github.com/spf13/afero
