GH_TUPLE=	\
		golang:mod:v0.32.0:golang_mod/vendor/golang.org/x/mod \
		golang:net:v0.49.0:golang_net/vendor/golang.org/x/net \
		golang:sync:v0.19.0:golang_sync/vendor/golang.org/x/sync \
		golang:text:v0.33.0:golang_text/vendor/golang.org/x/text \
		golang:tools:v0.41.0:golang_tools/vendor/golang.org/x/tools \
		iancoleman:strcase:v0.3.0:iancoleman_strcase/vendor/github.com/iancoleman/strcase \
		lyft:protoc-gen-star:v2.0.4:lyft_protoc_gen_star_v2/vendor/github.com/lyft/protoc-gen-star/v2 \
		protocolbuffers:protobuf-go:v1.36.11:protocolbuffers_protobuf_go/vendor/google.golang.org/protobuf \
		spf13:afero:v1.15.0:spf13_afero/vendor/github.com/spf13/afero
