# Created by: Luca Pizzamiglio <pizzamig@FreeBSD.org>

PKGNAMESUFFIX=	-node10

CONFLICTS_INSTALL=	yarn yarn-node14 yarn-node16 yarn-node17

USES=		nodejs:10,run

MASTERDIR=	${PORTSDIR}/www/yarn

.include "${MASTERDIR}/Makefile"
