CARGO_CRATES=	autocfg-1.1.0 \
		bitflags-1.3.2 \
		byteorder-1.4.3 \
		cfg-if-1.0.0 \
		kernel32-sys-0.2.2 \
		libc-0.2.126 \
		memoffset-0.6.5 \
		named_pipe-0.2.4 \
		nix-0.24.2 \
		winapi-0.2.8 \
		winapi-build-0.1.1
