GH_TUPLE=	\
		9fans:go:96bdba94b63f:9fans_go/vendor/9fans.net/go \
		BurntSushi:toml:v1.6.0:burntsushi_toml/vendor/github.com/BurntSushi/toml \
		FiloSottile:edwards25519:v1.2.0:filosottile_edwards25519/vendor/filippo.io/edwards25519 \
		akutz:memconn:v0.1.0:akutz_memconn/vendor/github.com/akutz/memconn \
		alexbrainman:sspi:1a75b4708caa:alexbrainman_sspi/vendor/github.com/alexbrainman/sspi \
		anmitsu:go-shlex:38f4b401e2be:anmitsu_go_shlex/vendor/github.com/anmitsu/go-shlex \
		aws:aws-sdk-go-v2:config/v1.32.17:aws_aws_sdk_go_v2_config \
		aws:aws-sdk-go-v2:credentials/v1.19.16:aws_aws_sdk_go_v2_credentials \
		aws:aws-sdk-go-v2:feature/ec2/imds/v1.18.23:aws_aws_sdk_go_v2_imds \
		aws:aws-sdk-go-v2:internal/configsources/v1.4.30:aws_aws_sdk_go_v2_configsources \
		aws:aws-sdk-go-v2:internal/endpoints/v2.7.30:aws_aws_sdk_go_v2_v2 \
		aws:aws-sdk-go-v2:internal/v4a/v1.4.24:aws_aws_sdk_go_v2_v4a \
		aws:aws-sdk-go-v2:service/internal/accept-encoding/v1.13.13:aws_aws_sdk_go_v2_accept_encoding \
		aws:aws-sdk-go-v2:service/internal/presigned-url/v1.13.30:aws_aws_sdk_go_v2_presigned_url \
		aws:aws-sdk-go-v2:service/signin/v1.0.11:aws_aws_sdk_go_v2_signin \
		aws:aws-sdk-go-v2:service/ssm/v1.45.0:aws_aws_sdk_go_v2_ssm \
		aws:aws-sdk-go-v2:service/sso/v1.30.17:aws_aws_sdk_go_v2_sso \
		aws:aws-sdk-go-v2:service/ssooidc/v1.35.21:aws_aws_sdk_go_v2_ssooidc \
		aws:aws-sdk-go-v2:service/sts/v1.42.1:aws_aws_sdk_go_v2_sts \
		aws:aws-sdk-go-v2:v1.42.1:aws_aws_sdk_go_v2/vendor/github.com/aws/aws-sdk-go-v2 \
		aws:smithy-go:v1.27.3:aws_smithy_go/vendor/github.com/aws/smithy-go \
		axiomhq:hyperloglog:84253e514e02:axiomhq_hyperloglog/vendor/github.com/axiomhq/hyperloglog \
		chromedp:cdproto:dc233986426f:chromedp_cdproto/vendor/github.com/chromedp/cdproto \
		chromedp:chromedp:v0.16.0:chromedp_chromedp/vendor/github.com/chromedp/chromedp \
		chromedp:sysutil:v1.1.0:chromedp_sysutil/vendor/github.com/chromedp/sysutil \
		coder:websocket:v1.8.14:coder_websocket/vendor/github.com/coder/websocket \
		coreos:go-iptables:65c67c9f46e6:coreos_go_iptables/vendor/github.com/coreos/go-iptables \
		creachadair:msync:v0.8.1:creachadair_msync/vendor/github.com/creachadair/msync \
		creack:pty:v1.1.24:creack_pty/vendor/github.com/creack/pty \
		dblohm7:wingoes:a09d6be7affa:dblohm7_wingoes/vendor/github.com/dblohm7/wingoes \
		dgryski:go-metro:280f6062b5bc:dgryski_go_metro/vendor/github.com/dgryski/go-metro \
		digitalocean:go-smbios:390a4f403a8e:digitalocean_go_smbios/vendor/github.com/digitalocean/go-smbios \
		djherbis:times:v1.6.0:djherbis_times/vendor/github.com/djherbis/times \
		dominikh:go-tools:v0.8.0-rc.1:dominikh_go_tools/vendor/honnef.co/go/tools \
		fxamacker:cbor:v2.9.0:fxamacker_cbor_v2/vendor/github.com/fxamacker/cbor/v2 \
		gaissmai:bart:v0.26.1:gaissmai_bart/vendor/github.com/gaissmai/bart \
		go-json-experiment:json:01eb4420fa68:go_json_experiment_json/vendor/github.com/go-json-experiment/json \
		go-ole:go-ole:v1.3.0:go_ole_go_ole/vendor/github.com/go-ole/go-ole \
		go4org:go4:3075585bcbeb:go4org_go4_1/vendor/go4.org/netipx \
		go4org:go4:ae6ca9944745:go4org_go4/vendor/go4.org/mem \
		go4org:hashtriemap:45fcf11fca0e:go4org_hashtriemap/vendor/github.com/go4org/hashtriemap \
		go4org:plan9netshell:788daa080737:go4org_plan9netshell/vendor/github.com/go4org/plan9netshell \
		gobwas:httphead:v0.1.0:gobwas_httphead/vendor/github.com/gobwas/httphead \
		gobwas:pool:v0.2.1:gobwas_pool/vendor/github.com/gobwas/pool \
		gobwas:ws:v1.4.0:gobwas_ws/vendor/github.com/gobwas/ws \
		godbus:dbus:v5.2.2:godbus_dbus_v5/vendor/github.com/godbus/dbus/v5 \
		golang:crypto:v0.55.0:golang_crypto/vendor/golang.org/x/crypto \
		golang:exp:746e56fc9e2f:golang_exp/vendor/golang.org/x/exp \
		golang:groupcache:2c02b8208cf8:golang_groupcache/vendor/github.com/golang/groupcache \
		golang:mod:v0.38.0:golang_mod/vendor/golang.org/x/mod \
		golang:net:v0.58.0:golang_net/vendor/golang.org/x/net \
		golang:sync:v0.22.0:golang_sync/vendor/golang.org/x/sync \
		golang:sys:v0.47.0:golang_sys/vendor/golang.org/x/sys \
		golang:term:v0.45.0:golang_term/vendor/golang.org/x/term \
		golang:text:v0.41.0:golang_text/vendor/golang.org/x/text \
		golang:time:v0.15.0:golang_time/vendor/golang.org/x/time \
		golang:tools:v0.48.0:golang_tools/vendor/golang.org/x/tools \
		google:btree:v1.1.3:google_btree/vendor/github.com/google/btree \
		google:go-cmp:v0.7.0:google_go_cmp/vendor/github.com/google/go-cmp \
		google:go-tpm:v0.9.4:google_go_tpm/vendor/github.com/google/go-tpm \
		google:gvisor:573d5e7127a8:google_gvisor/vendor/gvisor.dev/gvisor \
		google:nftables:5e242ec57806:google_nftables/vendor/github.com/google/nftables \
		google:uuid:v1.6.0:google_uuid/vendor/github.com/google/uuid \
		hdevalence:ed25519consensus:v0.2.0:hdevalence_ed25519consensus/vendor/github.com/hdevalence/ed25519consensus \
		huin:goupnp:v1.3.0:huin_goupnp/vendor/github.com/huin/goupnp \
		illarion:gonotify:v3.0.2:illarion_gonotify_v3/vendor/github.com/illarion/gonotify/v3 \
		insomniacslk:dhcp:15c9b8791914:insomniacslk_dhcp/vendor/github.com/insomniacslk/dhcp \
		jellydator:ttlcache:v3.1.0:jellydator_ttlcache_v3/vendor/github.com/jellydator/ttlcache/v3 \
		jmespath:go-jmespath:v0.4.0:jmespath_go_jmespath/vendor/github.com/jmespath/go-jmespath \
		jsimonetti:rtnetlink:v1.4.1:jsimonetti_rtnetlink/vendor/github.com/jsimonetti/rtnetlink \
		klauspost:compress:v1.19.1:klauspost_compress/vendor/github.com/klauspost/compress \
		kortschak:wol:da482cc4850a:kortschak_wol/vendor/github.com/kortschak/wol \
		kr:fs:v0.1.0:kr_fs/vendor/github.com/kr/fs \
		mdlayher:genetlink:v1.3.2:mdlayher_genetlink/vendor/github.com/mdlayher/genetlink \
		mdlayher:netlink:fbb4dce95f42:mdlayher_netlink/vendor/github.com/mdlayher/netlink \
		mdlayher:sdnotify:v1.0.0:mdlayher_sdnotify/vendor/github.com/mdlayher/sdnotify \
		mdlayher:socket:v0.5.1:mdlayher_socket/vendor/github.com/mdlayher/socket \
		mitchellh:go-ps:v1.0.0:mitchellh_go_ps/vendor/github.com/mitchellh/go-ps \
		peterbourgon:ff:v4.0.0-beta.1:peterbourgon_ff_v4/vendor/github.com/peterbourgon/ff/v4 \
		pierrec:lz4:v4.1.26:pierrec_lz4_v4/vendor/github.com/pierrec/lz4/v4 \
		pires:go-proxyproto:v0.8.1:pires_go_proxyproto/vendor/github.com/pires/go-proxyproto \
		pkg:sftp:v1.13.6:pkg_sftp/vendor/github.com/pkg/sftp \
		safchain:ethtool:v0.3.0:safchain_ethtool/vendor/github.com/safchain/ethtool \
		tailscale:certstore:3638fb84b77d:tailscale_certstore/vendor/github.com/tailscale/certstore \
		tailscale:gliderssh:1a0f895faf28:tailscale_gliderssh/vendor/github.com/tailscale/gliderssh \
		tailscale:go-winio:c4f33415bf55:tailscale_go_winio/vendor/github.com/tailscale/go-winio \
		tailscale:hujson:ecc657c15afd:tailscale_hujson/vendor/github.com/tailscale/hujson \
		tailscale:netlink:4d49adab4de7:tailscale_netlink/vendor/github.com/tailscale/netlink \
		tailscale:peercred:35a0c7bd7edc:tailscale_peercred/vendor/github.com/tailscale/peercred \
		tailscale:tailscale:31d8badb3bfb:tailscale_tailscale/vendor/tailscale.com \
		tailscale:web-client-prebuilt:d4cd19a26976:tailscale_web_client_prebuilt/vendor/github.com/tailscale/web-client-prebuilt \
		tailscale:wf:6fbb0a674ee6:tailscale_wf/vendor/github.com/tailscale/wf \
		tailscale:wireguard-go:e855235c55a2:tailscale_wireguard_go/vendor/github.com/tailscale/wireguard-go \
		tailscale:xnet:8497ac4dab2e:tailscale_xnet/vendor/github.com/tailscale/xnet \
		u-root:u-root:v0.14.0:u_root_u_root/vendor/github.com/u-root/u-root \
		u-root:uio:d2acac8f3701:u_root_uio/vendor/github.com/u-root/uio \
		vishvananda:netns:v0.0.5:vishvananda_netns/vendor/github.com/vishvananda/netns \
		wireguard:wireguard-go:v0.5.3:wireguard_wireguard_go/vendor/golang.zx2c4.com/wireguard/windows \
		x448:float16:v0.8.4:x448_float16/vendor/github.com/x448/float16
		# Mirrors for the following packages are not currently known, please look them up and handle these tuples manually:
		#	::0fa3db229ce2:group_name/vendor/golang.zx2c4.com/wintun (from git.zx2c4.com/wintun-go@0fa3db229ce2)
		#	::2842357ff358:group_name/vendor/golang.org/x/exp/typeparams (from go.googlesource.com/exp/typeparams@2842357ff358)
post-extract:
	@${RM} -r ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/config
	@${RLN} ${WRKSRC_aws_aws_sdk_go_v2_config}/config ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/config
	@${RM} -r ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/credentials
	@${RLN} ${WRKSRC_aws_aws_sdk_go_v2_credentials}/credentials ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/credentials
	@${RM} -r ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/feature/ec2/imds
	@${RLN} ${WRKSRC_aws_aws_sdk_go_v2_imds}/feature/ec2/imds ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/feature/ec2/imds
	@${RM} -r ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/internal/configsources
	@${RLN} ${WRKSRC_aws_aws_sdk_go_v2_configsources}/internal/configsources ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/internal/configsources
	@${RM} -r ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2
	@${RLN} ${WRKSRC_aws_aws_sdk_go_v2_v2}/internal/endpoints/v2 ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2
	@${RM} -r ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/internal/v4a
	@${RLN} ${WRKSRC_aws_aws_sdk_go_v2_v4a}/internal/v4a ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/internal/v4a
	@${RM} -r ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding
	@${RLN} ${WRKSRC_aws_aws_sdk_go_v2_accept_encoding}/service/internal/accept-encoding ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding
	@${RM} -r ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url
	@${RLN} ${WRKSRC_aws_aws_sdk_go_v2_presigned_url}/service/internal/presigned-url ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url
	@${RM} -r ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/service/signin
	@${RLN} ${WRKSRC_aws_aws_sdk_go_v2_signin}/service/signin ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/service/signin
	@${RM} -r ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/service/ssm
	@${RLN} ${WRKSRC_aws_aws_sdk_go_v2_ssm}/service/ssm ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/service/ssm
	@${RM} -r ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/service/sso
	@${RLN} ${WRKSRC_aws_aws_sdk_go_v2_sso}/service/sso ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/service/sso
	@${RM} -r ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/service/ssooidc
	@${RLN} ${WRKSRC_aws_aws_sdk_go_v2_ssooidc}/service/ssooidc ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/service/ssooidc
	@${RM} -r ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/service/sts
	@${RLN} ${WRKSRC_aws_aws_sdk_go_v2_sts}/service/sts ${WRKSRC}/vendor/github.com/aws/aws-sdk-go-v2/service/sts
