GH_TUPLE=	\
		C2SP:CCTV:4448f2097b2d:c2sp_cctv_age/vendor/c2sp.org/CCTV \
		FiloSottile:edwards25519:v1.2.0:filosottile_edwards25519/vendor/filippo.io/edwards25519 \
		FiloSottile:hpke:v0.4.0:filosottile_hpke/vendor/filippo.io/hpke \
		FiloSottile:nistec:v0.0.4:filosottile_nistec/vendor/filippo.io/nistec \
		golang:crypto:v0.55.0:golang_crypto/vendor/golang.org/x/crypto \
		golang:sys:v0.47.0:golang_sys/vendor/golang.org/x/sys \
		golang:term:v0.45.0:golang_term/vendor/golang.org/x/term \
		golang:tools:v0.49.0:golang_tools/vendor/golang.org/x/tools \
		rogpeppe:go-internal:v1.16.0:rogpeppe_go_internal/vendor/github.com/rogpeppe/go-internal
