GH_TUPLE=	\
		braydonk:yaml:v0.9.0:braydonk_yaml/vendor/github.com/braydonk/yaml \
		docker:cli:v29.6.2:docker_cli/vendor/github.com/docker/cli \
		docker:docker-credential-helpers:v0.9.8:docker_docker_credential_helpers/vendor/github.com/docker/docker-credential-helpers \
		golang:oauth2:v0.36.0:golang_oauth2/vendor/golang.org/x/oauth2 \
		golang:sync:v0.22.0:golang_sync/vendor/golang.org/x/sync \
		golang:sys:v0.47.0:golang_sys/vendor/golang.org/x/sys \
		google:go-cmp:v0.7.0:google_go_cmp/vendor/github.com/google/go-cmp \
		google:go-containerregistry:v0.21.7:google_go_containerregistry/vendor/github.com/google/go-containerregistry \
		google:go-github:v89.0.0:google_go_github_v89/vendor/github.com/google/go-github/v89 \
		google:go-querystring:v1.2.0:google_go_querystring/vendor/github.com/google/go-querystring \
		gotestyourself:gotest.tools:v3.5.2:gotestyourself_gotest_tools/vendor/gotest.tools/v3 \
		klauspost:compress:v1.19.0:klauspost_compress/vendor/github.com/klauspost/compress \
		opencontainers:go-digest:v1.0.0:opencontainers_go_digest/vendor/github.com/opencontainers/go-digest \
		opencontainers:image-spec:v1.1.1:opencontainers_image_spec/vendor/github.com/opencontainers/image-spec \
		sirupsen:logrus:v1.9.4:sirupsen_logrus/vendor/github.com/sirupsen/logrus
