#

PORTNAME=	util-linux
PORTVERSION=	2.23.2
DISTVERSIONSUFFIX=	-65.el7
CATEGORIES=	local linux sysutils

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	Utilities for managing filesystem extended attributes (CentOS ${LINUX_DIST_VER})

LICENSE=	GPLv3+

USES=		linux:c7
USE_LINUX_RPM=	nolib
OPTIONS_DEFINE=	DOCS
PLIST=		${PKGDIR}/pkg-plist

.include <bsd.port.mk>
