# Created by: Devon H. O'Dell <devon.odell@gmail.com>
# $FreeBSD: head/lang/go/Makefile 524508 2020-01-28 18:26:16Z jlaffaye $

PORTNAME=	go113
PORTVERSION=	1.13.15
PORTEPOCH=	1
CATEGORIES=	lang
MASTER_SITES=	https://golang.org/dl/
DISTNAME=	go${PORTVERSION}.src

MAINTAINER=	none@FreeBSD.org
COMMENT=	Go programming language

LICENSE=	BSD3CLAUSE

BUILD_DEPENDS=	go:lang/go

USES=		shebangfix
SHEBANG_LANG=	sh perl
SHEBANG_FILES=	misc/benchcmp \
		misc/nacl/go_nacl_*_exec \
		misc/wasm/go_js_wasm_exec \
		src/net/http/cgi/testdata/test.cgi
SHEBANG_GLOB=	*.bash *.pl *.sh

sh_OLD_CMD=	/bin/bash "/usr/bin/env bash"
sh_CMD=		${SH}

WRKSRC=		${WRKDIR}/go
ONLY_FOR_ARCHS=	i386 amd64 armv6 armv7

OPTIONS_DEFINE_i386=	GO387
GO387_DESC=	Do not generate code with SSE2 (for old x86 CPU)

.include <bsd.port.pre.mk>

.if ${ARCH} == i386
GOARCH=386
.elif ${ARCH} == "amd64"
GOARCH=amd64
.elif ${ARCH} == armv6 || ${ARCH} == armv7
GOARCH=arm
GOARM=${ARCH:C/armv//}
.else
IGNORE=		unknown arch ${ARCH}
.endif

.ifdef QEMU_EMULATING
IGNORE=		fails to build with qemu-user-static
.endif

.if ${PORT_OPTIONS:MGO387}
GO386=387
.endif

PLIST_SUB+=	opsys_ARCH=${OPSYS:tl}_${GOARCH}

post-patch:
#have been used ${SED} -i '' instead of ${REINPLACE_CMD} to avoid src/make.bash.bak in result package. remove $(type -ap go)
	${REINPLACE_CMD} -e 's|^if ulimit -T|false \&\& &|' ${WRKSRC}/src/run.bash
	${REINPLACE_CMD} -e 's|\$$([[:space:]]*type[[:space:]][^)]*)|""|' ${WRKSRC}/src/make.bash
	${FIND} ${WRKSRC}/src \( -name '*.orig' -o -name '*.bak' \) -delete

do-build:
	cd ${WRKSRC}/src && \
		GOROOT=${WRKSRC} GOROOT_FINAL=${PREFIX}/${PORTNAME} \
		GOROOT_BOOTSTRAP=${LOCALBASE}/go \
		GOBIN= GOARCH=${GOARCH} GOOS=${OPSYS:tl} \
		GO386=${GO386} GOARM=${GOARM} CGO_ENABLED=1 \
		${SH} make.bash -v
	${RM} -r ${WRKSRC}/pkg/obj \
	    ${WRKSRC}/pkg/bootstrap \
	    ${WRKSRC}/pkg/${OPSYS:tl}_${GOARCH}/cmd

do-install:
#	${CP} -a ${WRKSRC} ${STAGEDIR}${PREFIX}
#	${MV} ${STAGEDIR}${PREFIX}/${WRKSRC:T} ${STAGEDIR}${PREFIX}/${PORTNAME}
	${CP} -a ${WRKSRC} ${STAGEDIR}${PREFIX}/${PORTNAME}

do-test:
	cd ${WRKSRC}/src && GOROOT=${WRKSRC} PATH=${WRKSRC}/bin:${PATH} ${SH} run.bash -no-rebuild -banner ""

pkg-plist: stage
	${RM} ${WRKDIR}/pkg-plist
	cd ${WRKSRC:H} && ${FIND} ${WRKSRC:T} -type f | \
		${SED} -e "s/\/${OPSYS:tl}_${GOARCH}\//\/%%opsys_ARCH%%\//g" -e "s/^${WRKSRC:T}/${PORTNAME}/" | \
		${SORT} >> ${WRKDIR}/pkg-plist
	${CP} ${WRKDIR}/pkg-plist ${.CURDIR}/pkg-plist

.include <bsd.port.post.mk>
